adb pull /system/bin/ATFWD-daemon ../../../vendor/lge/mako/proprietary/ATFWD-daemon
adb pull /system/bin/bridgemgrd ../../../vendor/lge/mako/proprietary/bridgemgrd
adb pull /system/bin/btnvtool ../../../vendor/lge/mako/proprietary/btnvtool
adb pull /system/bin/diag_klog ../../../vendor/lge/mako/proprietary/diag_klog
adb pull /system/bin/diag_mdlog ../../../vendor/lge/mako/proprietary/diag_mdlog
adb pull /system/bin/ds_fmc_appd ../../../vendor/lge/mako/proprietary/ds_fmc_appd
adb pull /system/bin/efsks ../../../vendor/lge/mako/proprietary/efsks
adb pull /system/bin/hci_qcomm_init ../../../vendor/lge/mako/proprietary/hci_qcomm_init
adb pull /system/bin/ks ../../../vendor/lge/mako/proprietary/ks
adb pull /system/bin/mm-audio-send-cal ../../../vendor/lge/mako/proprietary/mm-audio-send-cal
adb pull /system/bin/mm-qcamera-daemon ../../../vendor/lge/mako/proprietary/mm-qcamera-daemon
adb pull /system/bin/mpdecision ../../../vendor/lge/mako/proprietary/mpdecision
adb pull /system/bin/netmgrd ../../../vendor/lge/mako/proprietary/netmgrd
adb pull /system/bin/nl_listener ../../../vendor/lge/mako/proprietary/nl_listener
adb pull /system/bin/PktRspTest ../../../vendor/lge/mako/proprietary/PktRspTest
adb pull /system/bin/port-bridge ../../../vendor/lge/mako/proprietary/port-bridge
adb pull /system/bin/qcks ../../../vendor/lge/mako/proprietary/qcks
adb pull /system/bin/qmuxd ../../../vendor/lge/mako/proprietary/qmuxd
adb pull /system/bin/qseecomd ../../../vendor/lge/mako/proprietary/qseecomd
adb pull /system/bin/radish ../../../vendor/lge/mako/proprietary/radish
adb pull /system/bin/rmt_storage ../../../vendor/lge/mako/proprietary/rmt_storage
adb pull /system/bin/sensors.qcom ../../../vendor/lge/mako/proprietary/sensors.qcom
adb pull /system/bin/sns_cm_conc_test ../../../vendor/lge/mako/proprietary/sns_cm_conc_test
adb pull /system/bin/sns_cm_test ../../../vendor/lge/mako/proprietary/sns_cm_test
adb pull /system/bin/sns_debug_file_test ../../../vendor/lge/mako/proprietary/sns_debug_file_test
adb pull /system/bin/sns_dsps_tc0001 ../../../vendor/lge/mako/proprietary/sns_dsps_tc0001
adb pull /system/bin/sns_smr_loopback_test ../../../vendor/lge/mako/proprietary/sns_smr_loopback_test
adb pull /system/bin/test_diag ../../../vendor/lge/mako/proprietary/test_diag
adb pull /system/bin/thermald ../../../vendor/lge/mako/proprietary/thermald
adb pull /system/bin/usbhub ../../../vendor/lge/mako/proprietary/usbhub
adb pull /system/bin/usbhub_init ../../../vendor/lge/mako/proprietary/usbhub_init
adb pull /system/bin/v4l2-qcamera-app ../../../vendor/lge/mako/proprietary/v4l2-qcamera-app
adb pull /system/etc/diag.cfg ../../../vendor/lge/mako/proprietary/diag.cfg
adb pull /system/etc/DxHDCP.cfg ../../../vendor/lge/mako/proprietary/DxHDCP.cfg
adb pull /system/etc/firmware/a225p5_pm4.fw ../../../vendor/lge/mako/proprietary/a225p5_pm4.fw
adb pull /system/etc/firmware/a225_pfp.fw ../../../vendor/lge/mako/proprietary/a225_pfp.fw
adb pull /system/etc/firmware/a225_pm4.fw ../../../vendor/lge/mako/proprietary/a225_pm4.fw
adb pull /system/etc/firmware/a300_pfp.fw ../../../vendor/lge/mako/proprietary/a300_pfp.fw
adb pull /system/etc/firmware/a300_pm4.fw ../../../vendor/lge/mako/proprietary/a300_pm4.fw
adb pull /system/etc/firmware/leia_pfp_470.fw ../../../vendor/lge/mako/proprietary/leia_pfp_470.fw
adb pull /system/etc/firmware/leia_pm4_470.fw ../../../vendor/lge/mako/proprietary/leia_pm4_470.fw
adb pull /system/etc/firmware/vidc.b00 ../../../vendor/lge/mako/proprietary/vidc.b00
adb pull /system/etc/firmware/vidc.b01 ../../../vendor/lge/mako/proprietary/vidc.b01
adb pull /system/etc/firmware/vidc.b02 ../../../vendor/lge/mako/proprietary/vidc.b02
adb pull /system/etc/firmware/vidc.b03 ../../../vendor/lge/mako/proprietary/vidc.b03
adb pull /system/etc/firmware/vidc.mdt ../../../vendor/lge/mako/proprietary/vidc.mdt
adb pull /system/etc/firmware/vidcfw.elf ../../../vendor/lge/mako/proprietary/vidcfw.elf
adb pull /system/etc/firmware/vidc_1080p.fw ../../../vendor/lge/mako/proprietary/vidc_1080p.fw
adb pull /system/etc/firmware/wcd9310/wcd9310_anc.bin ../../../vendor/lge/mako/proprietary/wcd9310_anc.bin
adb pull /system/etc/firmware/wcd9310/wcd9310_mbhc.bin ../../../vendor/lge/mako/proprietary/wcd9310_mbhc.bin
adb pull /system/lib/egl/eglsubAndroid.so ../../../vendor/lge/mako/proprietary/eglsubAndroid.so
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/lge/mako/proprietary/libEGL_adreno200.so
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/lge/mako/proprietary/libGLESv1_CM_adreno200.so
adb pull /system/lib/egl/libGLESv2S3D_adreno200.so ../../../vendor/lge/mako/proprietary/libGLESv2S3D_adreno200.so
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/lge/mako/proprietary/libGLESv2_adreno200.so
adb pull /system/lib/egl/libplayback_adreno200.so ../../../vendor/lge/mako/proprietary/libplayback_adreno200.so
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/lge/mako/proprietary/libq3dtools_adreno200.so
adb pull /system/lib/hw/sensors.msm8960.so ../../../vendor/lge/mako/proprietary/sensors.msm8960.so
adb pull /system/lib/libacdbloader.so ../../../vendor/lge/mako/proprietary/libacdbloader.so
adb pull /system/lib/libAKM.so ../../../vendor/lge/mako/proprietary/libAKM.so
adb pull /system/lib/libalsautils.so ../../../vendor/lge/mako/proprietary/libalsautils.so
adb pull /system/lib/libaudcal.so ../../../vendor/lge/mako/proprietary/libaudcal.so
adb pull /system/lib/libaudioalsa.so ../../../vendor/lge/mako/proprietary/libaudioalsa.so
adb pull /system/lib/libaudioparsers.so ../../../vendor/lge/mako/proprietary/libaudioparsers.so
adb pull /system/lib/libC2D2.so ../../../vendor/lge/mako/proprietary/libC2D2.so
adb pull /system/lib/libc2d2_a3xx.so ../../../vendor/lge/mako/proprietary/libc2d2_a3xx.so
adb pull /system/lib/libc2d2_z180.so ../../../vendor/lge/mako/proprietary/libc2d2_z180.so
adb pull /system/lib/libcamera_fast_af.so ../../../vendor/lge/mako/proprietary/libcamera_fast_af.so
adb pull /system/lib/libchromatix_imx111_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_imx111_default_video.so
adb pull /system/lib/libchromatix_imx111_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_imx111_preview.so
adb pull /system/lib/libchromatix_imx111_zsl.so ../../../vendor/lge/mako/proprietary/libchromatix_imx111_zsl.so
adb pull /system/lib/libchromatix_imx119_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_imx119_default_video.so
adb pull /system/lib/libchromatix_imx119_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_imx119_preview.so
adb pull /system/lib/libchromatix_mt9e013_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_mt9e013_default_video.so
adb pull /system/lib/libchromatix_mt9e013_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_mt9e013_preview.so
adb pull /system/lib/libchromatix_mt9e013_video_hfr.so ../../../vendor/lge/mako/proprietary/libchromatix_mt9e013_video_hfr.so
adb pull /system/lib/libchromatix_ov5647_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_ov5647_default_video.so
adb pull /system/lib/libchromatix_ov5647_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_ov5647_preview.so
adb pull /system/lib/libchromatix_ov5647_video_hfr.so ../../../vendor/lge/mako/proprietary/libchromatix_ov5647_video_hfr.so
adb pull /system/lib/libchromatix_ov8825_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_ov8825_default_video.so
adb pull /system/lib/libchromatix_ov8825_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_ov8825_preview.so
adb pull /system/lib/libchromatix_ov9726_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_ov9726_default_video.so
adb pull /system/lib/libchromatix_ov9726_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_ov9726_preview.so
adb pull /system/lib/libchromatix_s5k4e1_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_s5k4e1_default_video.so
adb pull /system/lib/libchromatix_s5k4e1_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_s5k4e1_preview.so
adb pull /system/lib/libchromatix_vx6953_default_video.so ../../../vendor/lge/mako/proprietary/libchromatix_vx6953_default_video.so
adb pull /system/lib/libchromatix_vx6953_preview.so ../../../vendor/lge/mako/proprietary/libchromatix_vx6953_preview.so
adb pull /system/lib/libCommandSvc.so ../../../vendor/lge/mako/proprietary/libCommandSvc.so
adb pull /system/lib/libconfigdb.so ../../../vendor/lge/mako/proprietary/libconfigdb.so
adb pull /system/lib/libcsd-client.so ../../../vendor/lge/mako/proprietary/libcsd-client.so
adb pull /system/lib/libdiag.so ../../../vendor/lge/mako/proprietary/libdiag.so
adb pull /system/lib/libdrmdiag.so ../../../vendor/lge/mako/proprietary/libdrmdiag.so
adb pull /system/lib/libdrmfs.so ../../../vendor/lge/mako/proprietary/libdrmfs.so
adb pull /system/lib/libdrmtime.so ../../../vendor/lge/mako/proprietary/libdrmtime.so
adb pull /system/lib/libdsi_netctrl.so ../../../vendor/lge/mako/proprietary/libdsi_netctrl.so
adb pull /system/lib/libdsprofile.so ../../../vendor/lge/mako/proprietary/libdsprofile.so
adb pull /system/lib/libdss.so ../../../vendor/lge/mako/proprietary/libdss.so
adb pull /system/lib/libdsucsd.so ../../../vendor/lge/mako/proprietary/libdsucsd.so
adb pull /system/lib/libdsutils.so ../../../vendor/lge/mako/proprietary/libdsutils.so
adb pull /system/lib/libDxHdcp.so ../../../vendor/lge/mako/proprietary/libDxHdcp.so
adb pull /system/lib/libgemini.so ../../../vendor/lge/mako/proprietary/libgemini.so
adb pull /system/lib/libgsl.so ../../../vendor/lge/mako/proprietary/libgsl.so
adb pull /system/lib/libI420colorconvert.so ../../../vendor/lge/mako/proprietary/libI420colorconvert.so
adb pull /system/lib/libidl.so ../../../vendor/lge/mako/proprietary/libidl.so
adb pull /system/lib/libimage-jpeg-dec-omx-comp.so ../../../vendor/lge/mako/proprietary/libimage-jpeg-dec-omx-comp.so
adb pull /system/lib/libimage-jpeg-enc-omx-comp.so ../../../vendor/lge/mako/proprietary/libimage-jpeg-enc-omx-comp.so
adb pull /system/lib/libimage-omx-common.so ../../../vendor/lge/mako/proprietary/libimage-omx-common.so
adb pull /system/lib/libllvm-a3xx.so ../../../vendor/lge/mako/proprietary/libllvm-a3xx.so
adb pull /system/lib/libllvm-arm.so ../../../vendor/lge/mako/proprietary/libllvm-arm.so
adb pull /system/lib/libloc_api_v02.so ../../../vendor/lge/mako/proprietary/libloc_api_v02.so
adb pull /system/lib/libmercury.so ../../../vendor/lge/mako/proprietary/libmercury.so
adb pull /system/lib/libmm-color-convertor.so ../../../vendor/lge/mako/proprietary/libmm-color-convertor.so
adb pull /system/lib/libmmcamera_faceproc.so ../../../vendor/lge/mako/proprietary/libmmcamera_faceproc.so
adb pull /system/lib/libmmcamera_frameproc.so ../../../vendor/lge/mako/proprietary/libmmcamera_frameproc.so
adb pull /system/lib/libmmcamera_hdr_lib.so ../../../vendor/lge/mako/proprietary/libmmcamera_hdr_lib.so
adb pull /system/lib/libmmcamera_image_stab.so ../../../vendor/lge/mako/proprietary/libmmcamera_image_stab.so
adb pull /system/lib/libmmcamera_statsproc31.so ../../../vendor/lge/mako/proprietary/libmmcamera_statsproc31.so
adb pull /system/lib/libmmcamera_wavelet_lib.so ../../../vendor/lge/mako/proprietary/libmmcamera_wavelet_lib.so
adb pull /system/lib/libmmipl.so ../../../vendor/lge/mako/proprietary/libmmipl.so
adb pull /system/lib/libmmjpeg.so ../../../vendor/lge/mako/proprietary/libmmjpeg.so
adb pull /system/lib/libmmjps.so ../../../vendor/lge/mako/proprietary/libmmjps.so
adb pull /system/lib/libmmmpo.so ../../../vendor/lge/mako/proprietary/libmmmpo.so
adb pull /system/lib/libmmmpod.so ../../../vendor/lge/mako/proprietary/libmmmpod.so
adb pull /system/lib/libmmstillomx.so ../../../vendor/lge/mako/proprietary/libmmstillomx.so
adb pull /system/lib/libmorpho_noise_reduction.so ../../../vendor/lge/mako/proprietary/libmorpho_noise_reduction.so
adb pull /system/lib/libnetmgr.so ../../../vendor/lge/mako/proprietary/libnetmgr.so
adb pull /system/lib/liboemcamera.so ../../../vendor/lge/mako/proprietary/liboemcamera.so
adb pull /system/lib/libOmxAacDec.so ../../../vendor/lge/mako/proprietary/libOmxAacDec.so
adb pull /system/lib/libOmxWmaDec.so ../../../vendor/lge/mako/proprietary/libOmxWmaDec.so
adb pull /system/lib/libOpenCL.so ../../../vendor/lge/mako/proprietary/libOpenCL.so
adb pull /system/lib/libOpenVG.so ../../../vendor/lge/mako/proprietary/libOpenVG.so
adb pull /system/lib/libqcci_legacy.so ../../../vendor/lge/mako/proprietary/libqcci_legacy.so
adb pull /system/lib/libqdi.so ../../../vendor/lge/mako/proprietary/libqdi.so
adb pull /system/lib/libqdp.so ../../../vendor/lge/mako/proprietary/libqdp.so
adb pull /system/lib/libqmi.so ../../../vendor/lge/mako/proprietary/libqmi.so
adb pull /system/lib/libqmiservices.so ../../../vendor/lge/mako/proprietary/libqmiservices.so
adb pull /system/lib/libqmi_cci.so ../../../vendor/lge/mako/proprietary/libqmi_cci.so
adb pull /system/lib/libqmi_client_qmux.so ../../../vendor/lge/mako/proprietary/libqmi_client_qmux.so
adb pull /system/lib/libqmi_common_so.so ../../../vendor/lge/mako/proprietary/libqmi_common_so.so
adb pull /system/lib/libqmi_csi.so ../../../vendor/lge/mako/proprietary/libqmi_csi.so
adb pull /system/lib/libqmi_csvt_srvc.so ../../../vendor/lge/mako/proprietary/libqmi_csvt_srvc.so
adb pull /system/lib/libqmi_encdec.so ../../../vendor/lge/mako/proprietary/libqmi_encdec.so
adb pull /system/lib/libQSEEComAPI.so ../../../vendor/lge/mako/proprietary/libQSEEComAPI.so
adb pull /system/lib/libril-qc-qmi-1.so ../../../vendor/lge/mako/proprietary/libril-qc-qmi-1.so
adb pull /system/lib/libril-qcril-hook-oem.so ../../../vendor/lge/mako/proprietary/libril-qcril-hook-oem.so
adb pull /system/lib/libsc-a2xx.so ../../../vendor/lge/mako/proprietary/libsc-a2xx.so
adb pull /system/lib/libsc-a3xx.so ../../../vendor/lge/mako/proprietary/libsc-a3xx.so
adb pull /system/lib/libsensor1.so ../../../vendor/lge/mako/proprietary/libsensor1.so
adb pull /system/lib/libsensor_reg.so ../../../vendor/lge/mako/proprietary/libsensor_reg.so
adb pull /system/lib/libsensor_test.so ../../../vendor/lge/mako/proprietary/libsensor_test.so
adb pull /system/lib/libsensor_user_cal.so ../../../vendor/lge/mako/proprietary/libsensor_user_cal.so
adb pull /system/lib/libstagefright_hdcp.so ../../../vendor/lge/mako/proprietary/libstagefright_hdcp.so
adb pull /system/lib/libxml.so ../../../vendor/lge/mako/proprietary/libxml.so
adb pull /system/lib/lib_dlb_msd.so ../../../vendor/lge/mako/proprietary/lib_dlb_msd.so
adb pull /system/vendor/firmware/bcm2079x_firmware.ncd ../../../vendor/lge/mako/proprietary/bcm2079x_firmware.ncd
adb pull /system/vendor/firmware/bcm2079x_pre_firmware.ncd ../../../vendor/lge/mako/proprietary/bcm2079x_pre_firmware.ncd
adb pull /system/vendor/firmware/discretix/dxhdcp2.b00 ../../../vendor/lge/mako/proprietary/dxhdcp2.b00
adb pull /system/vendor/firmware/discretix/dxhdcp2.b01 ../../../vendor/lge/mako/proprietary/dxhdcp2.b01
adb pull /system/vendor/firmware/discretix/dxhdcp2.b02 ../../../vendor/lge/mako/proprietary/dxhdcp2.b02
adb pull /system/vendor/firmware/discretix/dxhdcp2.b03 ../../../vendor/lge/mako/proprietary/dxhdcp2.b03
adb pull /system/vendor/firmware/discretix/dxhdcp2.mdt ../../../vendor/lge/mako/proprietary/dxhdcp2.mdt
adb pull /system/vendor/lib/libdrmdecrypt.so ../../../vendor/lge/mako/proprietary/libdrmdecrypt.so